#!/usr/bin/env python3
"""Generate editor metadata and native parameter limits from the shared TSV.

The editor and native admission checks share parameter limits. Layout, packed
value presentation and active oscillator selection remain UI policy.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/editor/deep_editor_manifest.tsv"
OUTPUT = ROOT / "src/editor/deep_editor_manifest.js"
LIMITS = ROOT / "src/program_parameter_limits.h"

FIELDS = (
    "kind",
    "group",
    "param",
    "section",
    "subsection",
    "name",
    "value_type",
    "min",
    "max",
    "unit",
    "enum",
    "primary_offset",
    "status",
    "confidence",
    "notes",
    "bit_shift",
    "bit_width",
)


def integer(value: str):
    if not value:
        return None
    return int(value.lstrip("+"))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check generated files without rewriting them")
    args = parser.parse_args()
    with SOURCE.open(newline="", encoding="utf-8") as stream:
        source_rows = list(csv.DictReader(stream, delimiter="\t"))

    rows = []
    for source in source_rows:
        # TSV writers commonly omit empty trailing columns. Normalize those
        # missing cells so a whitespace-clean source remains byte-stable.
        row = {field: source.get(field) or "" for field in FIELDS}
        for field in ("group", "param", "min", "max", "primary_offset", "bit_shift", "bit_width"):
            row[field] = integer(row[field])
        row["enum"] = row["enum"].split("|") if row["enum"] else []
        rows.append(row)

    payload = {
        "schema": 1,
        "source": str(SOURCE.relative_to(ROOT)),
        "row_count": len(rows),
        "rows": rows,
    }
    text = (
        "// SPDX-License-Identifier: AGPL-3.0-only\n"
        "// Generated by scripts/gen_deep_editor_manifest.py; do not hand-edit.\n"
        "window.PROPHECY_DEEP_MANIFEST = "
        + json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
        + ";\n"
    )
    program = [row for row in rows if row["kind"] == "program"]
    assert [row["param"] for row in program] == list(range(1, len(program) + 1))
    oscillator = [row["param"] for row in program if row["section"] == "OSC-Specific Blocks"]
    assert oscillator == list(range(oscillator[0], oscillator[-1] + 1))
    ranges = [(1, 0)]  # parameter zero and reserved rows are not editor operations
    for row in program:
        if row["value_type"] == "reserved":
            ranges.append((1, 0))
        else:
            # Six catalogued controls have no numeric wire limits in the TSV.
            # Keep their protocol range instead of inventing display-unit limits.
            ranges.append((row["min"] if row["min"] is not None else -8192,
                           row["max"] if row["max"] is not None else 8191))
    limits = [
        "// SPDX-License-Identifier: AGPL-3.0-only",
        "// Generated by scripts/gen_deep_editor_manifest.py; do not hand-edit.",
        "#pragma once", "", "#include <cstddef>", "#include <cstdint>", "", "namespace prophecy {", "",
        "inline bool supportedProgramParameter(std::uint16_t address, std::int16_t value)",
        "{", "\tstruct Range { std::int16_t minimum, maximum; };",
        "\tstatic constexpr Range ranges[]{",
    ]
    for first in range(0, len(ranges), 8):
        entries = ", ".join("{%d, %d}" % pair for pair in ranges[first:first + 8])
        limits.append(f"\t\t{entries}, // {first}")
    limits += [
        "\t};", "\tconst std::size_t parameter = address & 0x0fff;",
        "\tconst auto slot = address >> 12;",
        "\tif (parameter >= sizeof(ranges) / sizeof(ranges[0])) return false;",
        f"\tconst bool oscillator = parameter >= {oscillator[0]} && parameter <= {oscillator[-1]};",
        "\tif (oscillator ? (slot != 1 && slot != 2) : slot != 0) return false;",
        "\tconst auto range = ranges[parameter];",
        "\treturn value >= range.minimum && value <= range.maximum;", "}", "", "}", "",
    ]
    for output, contents in ((OUTPUT, text), (LIMITS, "\n".join(limits))):
        if args.check:
            if not output.is_file() or output.read_text(encoding="utf-8") != contents:
                raise SystemExit(f"stale generated file: {output.relative_to(ROOT)}")
        else:
            output.write_text(contents, encoding="utf-8")
            print(f"wrote {output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
