#!/usr/bin/env python3
"""Generate the WebView deep-editor catalogue from the authoritative TSV.

The generated file is deliberately data-only.  UI policy (which rows are
editable, how packed values are presented, and oscillator ExID addressing)
lives in index.html so it can be reviewed independently of this generator.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/editor/deep_editor_manifest.tsv"
OUTPUT = ROOT / "src/editor/deep_editor_manifest.js"

FIELDS = (
    "kind",
    "group",
    "param",
    "section",
    "subsection",
    "name",
    "value_type",
    "min",
    "max",
    "unit",
    "enum",
    "primary_offset",
    "status",
    "confidence",
    "notes",
    "bit_shift",
    "bit_width",
)


def integer(value: str):
    if not value:
        return None
    return int(value.lstrip("+"))


def main() -> None:
    with SOURCE.open(newline="", encoding="utf-8") as stream:
        source_rows = list(csv.DictReader(stream, delimiter="\t"))

    rows = []
    for source in source_rows:
        # TSV writers commonly omit empty trailing columns. Normalize those
        # missing cells so a whitespace-clean source remains byte-stable.
        row = {field: source.get(field) or "" for field in FIELDS}
        for field in ("group", "param", "min", "max", "primary_offset", "bit_shift", "bit_width"):
            row[field] = integer(row[field])
        row["enum"] = row["enum"].split("|") if row["enum"] else []
        rows.append(row)

    payload = {
        "schema": 1,
        "source": str(SOURCE.relative_to(ROOT)),
        "row_count": len(rows),
        "rows": rows,
    }
    text = (
        "// SPDX-License-Identifier: AGPL-3.0-only\n"
        "// Generated by scripts/gen_deep_editor_manifest.py; do not hand-edit.\n"
        "window.PROPHECY_DEEP_MANIFEST = "
        + json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
        + ";\n"
    )
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
